name: Simple CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tampilkan pesan
        run: echo "Pipeline berhasil dijalankan"
 
      - name: Gunakan Secret
        run: echo "Secret key adalah ${{ secrets.MY_SECRET_KEY }}"