name: CI/CD Pipeline Production
on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist folder and index.html
        run: |
          mkdir -p dist
          echo "Ini adalah hasil build otomatis Artifact" > dist/index.html

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-build-web
          path: dist/
          retention-days: 7

  deploy-to-vps:
    runs-on: ubuntu-latest
    needs: build-app # Mewajibkan job build sukses dulu sebelum deploy jalan
    steps:
      # 1. Mengunduh hasil "masakan" (Artifact)
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: hasil-build-web
          path: dist/

      # 2. Kurir mengirim barang ke VPS menggunakan SCP Action
      - name: Copy Artifact to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html" # Sesuaikan path di VPS kalian

      # 3. Masuk ke VPS dan Restart Service
      - name: Execute Restart Command via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Memulai proses restart service di VPS..."
            # Di dunia nyata, ini berisi perintah pm2 restart atau docker restart
            echo "Deployment Production Sukses untuk penambahan baru Tugas 15!"