name: Deploy Final Project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            TARGET_DIR="/var/www/html/vps-monitor"
            
            # 1. Masuk ke direktori target
            sudo mkdir -p $TARGET_DIR
            sudo chown -R $USER:$USER $TARGET_DIR
            cd $TARGET_DIR

            # 2. Update kode (Karena file sudah di root, cukup pull biasa)
            if [ ! -d ".git" ]; then
              git clone https://github.com/ngebenis/BDS-Sanbercode-Devops-Batch-76.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # 3. Bersihkan folder tugas agar tidak mengganggu RAM/Storage
            rm -rf Tugas-* Final-Project/

            # 4. Install dependensi & Restart
            # --omit=dev menjaga penggunaan RAM tetap hemat (< 200MB)
            npm install --omit=dev
            
            # Restart menggunakan PM2
            pm2 delete vps-monitor || true
            pm2 start server.js --name "vps-monitor" --max-memory-restart 150M